### ISSUE TITLE
公共的css怎么在webpack中配置呢？

### ISSUE THREAD

**Issue by Chasen-Zhang** [liaohengfan/webpack-muilt-page#1]
公共的css怎么在webpack中配置呢？不想在每个页面引入

**Comment by liaohengfan** [comment]
css引入模块
添加css路径
"include": [
    "./src/styles.css"
]

示例:
{
              loader: 'css-loader',
"include": [
    "./src/styles.css"
],
              options: {
                minimize: true
              }
            }
